//------Generated by the Framework and can be changed-----//
//------Login Activity Sample with Util Functions-----//

package br.ufc.poc2.ui.CommonActivities

import android.content.Intent
import android.os.Bundle
import br.ufc.poc2.R
import br.ufc.poc2.controllers.LoginController

class LoginActivity : BaseActivity() {

    private lateinit var loginController: LoginController

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_login)

        loginController = LoginController(this)

       /*
       btnSignIn.setOnClickListener {
            loginController.signIn()
        }
        */
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        loginController.activityResult(requestCode, data)
    }
}