//------Generated by the Framework and must not be changed-----/
//------From Observer Pattern Interface-----//

package br.ufc.poc2.model.mapek.observer

interface IExecutionObserver {
        fun update()
}