//------Generated by the Framework and must not be changed-----//
package br.ufc.POC1.model.entities.sensors

//------Values  Entity Sensors -----//
class ValuesSensor(val idSensor:String, val value:Any) {
}