//------Generated by the Framework and can be changed-----//
//------GUnity of Work Pattern-----//

package br.ufc.frameworkkotlin.model.dao.data

import android.database.sqlite.SQLiteOpenHelper
import br.ufc.frameworkkotlin.model.dao.interfaces.IUnityofWork

class UnityofWork(val dbHelper: SQLiteOpenHelper):IUnityofWork{
    val db = dbHelper.writableDatabase

    override fun transaction() {
        val SQL_INFO = "BEGIN TRANSACTION"
        db?.execSQL(SQL_INFO)
    }

    override fun commit() {
        val SQL_INFO = "COMMIT TRANSACTION"
        db?.execSQL(SQL_INFO)
    }

    override fun rollback() {
        val SQL_INFO = "ROLLBACK TRANSACTION"
        db?.execSQL(SQL_INFO)
    }

}