//------Generated by the Framework and must not be changed-----/
//------From Observer Pattern Interface-----//

package br.ufc.POC1.model.mapek.observer

interface IAnalysisObserver {
        fun update()
}