//------Generated by the Framework and can be changed-----//
//------Samples of DB Entity-----//

package br.ufc.POC1.model.dao.DBEntities

data class Pessoa (var id: Int = 0, var nome:String = "") {}