//------Generated by the Framework and must not be changed-----//
//------Entity representing a Vertice Sensor for Knowledge Representation based on Classification Graph Template-----//
package br.ufc.POC1.model.entities

class VerticeSensor(val typeSensor: String) {
}