//------Generated by the Framework and must not be changed-----//
package br.ufc.frameworkkotlin.model.entities

//------Entity representing an adaptation rule-----//
class AdaptationRules(val adaptationList:MutableList<Adaptation>) {
    class Adaptation(var action:String, var contextList: MutableList<context>){}
    class context(var name:String, var signal:String, var value: String){}
}