//------Generated by the Framework and must not be changed-----//
//------Entity representing a Analysis Result for Planning and Execution Steps-----//
package br.ufc.frameworkkotlin.model.entities

class ResultEntry(val context:MutableList<Context>, val probability: Double, val finalStatus:String) {
}