//------Generated by the Framework and can be changed-----//
//------Action Sample Class-----//

package br.ufc.poc2.model.mapek.execution

import android.util.Log
import br.ufc.poc2.ui.MainActivity
import br.ufc.poc2.ui.CommonActivities.BaseActivity
import task.Task2

class TextAction: Task2() {
    override fun recebeToken(o: Any?) {}

    override fun retornaToken(): Any? {
        return null
    }

    override fun executar() {
        MainActivity.flagMonitoring = true
        //MainActivity.texto = "Danger"
        MainActivity.texto = BaseActivity.finalStatus !!
        Log.i("Text status",BaseActivity.finalStatus !! )
    }

    override fun retorno(): Any? {
        return null
    }

    override fun evaluate(o: Any) {
        BaseActivity.finalStatus = o as String

        ///Inicio verificação de Status especiais
       // if (BaseActivity.finalStatus !!.contains("Clapping Standing") || BaseActivity.finalStatus !!.contains("Fall"))
            executar()
        ///Fim de verificação de Status especiais

    }

    override fun run() {
        executar()
    }
}