//------Generated by the Framework and can be changed-----//
//------Sample of LoginController for Login Activity----//

package br.ufc.poc2.controllers

import android.content.Intent
import br.ufc.poc2.model.utils.Constants
import br.ufc.poc2.model.utils.GoogleApiUtil
import br.ufc.poc2.ui.CommonActivities.BaseActivity
import br.ufc.poc2.R

class LoginController(private val activity: BaseActivity) {

    private var googleApiClient: GoogleApiUtil = GoogleApiUtil(activity)

    fun signIn() {
        googleApiClient.signIn()
    }

    fun activityResult(requestCode: Int, data: Intent?) {
        if (requestCode == Constants.SIGN_IN && googleApiClient.googleResult(data) == true) {
  //          activity.startActivity(Intent(activity.baseContext, MenuActivity::class.java))
        } else {
            activity.showLongToast(activity.getString(R.string.login_failed), false)
        }
    }

    fun isLogged():Boolean{
        return googleApiClient.isLogged()
    }
}