//------Generated by the Framework and can be changed-----//
//------Login Activity Sample with Util Functions-----//

package br.ufc.frameworkkotlin.ui.CommonActivities

import android.content.Intent
import android.os.Bundle
import br.ufc.frameworkkotlin.R
import br.ufc.frameworkkotlin.controllers.LoginController

class LoginActivity : BaseActivity() {

    private lateinit var loginController: LoginController

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_login)

        loginController = LoginController(this)

       /* btnSignIn.setOnClickListener {
            loginController.signIn()
        }*/

/*
        if(loginController.isLogged()){
            this.startActivity(Intent(this.baseContext, MenuActivity::class.java))
        }*/
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        loginController.activityResult(requestCode, data)
    }
}