//------Generated by the Framework and can be changed-----//
//------Action Sample Class-----//
package br.ufc.POC1.model.mapek.execution

import task.Task2

class Action: Task2() {
    override fun executar() {
        TODO("Not yet implemented")
    }

    override fun retorno(): Any {
        TODO("Not yet implemented")
    }

    override fun recebeToken(p0: Any?) {
        TODO("Not yet implemented")
    }

    override fun retornaToken(): Any {
        TODO("Not yet implemented")
    }

    override fun evaluate(p0: Any?) {
        TODO("Not yet implemented")
    }
}