//------Generated by the Framework and can be changed-----//
//------Action Sample Class-----//

package br.ufc.POC1.model.mapek.execution

import android.content.Intent
import android.util.Log
import br.ufc.POC1.ui.AlertActivity
import br.ufc.POC1.ui.MainActivity
import br.ufc.POC1.ui.CommonActivities.BaseActivity
import task.Task2

class TextAction: Task2() {

    lateinit var context:BaseActivity

    override fun recebeToken(o: Any?) {}

    override fun retornaToken(): Any? {
        return null
    }

    override fun executar() {
        MainActivity.flagMonitoring = true
        //MainActivity.texto = "Danger"
        MainActivity.texto = BaseActivity.finalStatus !!
        Log.i("Text status",BaseActivity.finalStatus !! )

        AlertActivity.actions.add("texto")

        val intent = Intent(context, AlertActivity::class.java)
        context.startActivity(intent)

    }

    override fun retorno(): Any? {
        return null
    }

    override fun evaluate(o: Any) {
        val result = o as Pair<String,BaseActivity>
        BaseActivity.finalStatus  = o.first

        ///Inicio verificação de Status especiais
        context = o.second
        if (BaseActivity.finalStatus !!.contains("Clapping Standing") || BaseActivity.finalStatus !!.contains("Fall")||
            BaseActivity.finalStatus !!.contains("Hitting a wall"))
            executar()
        ///Fim de verificação de Status especiais
    }

    override fun run() {
        executar()
    }
}