//------Generated by the Framework and must not be changed-----/
//------From Observer Pattern Interface-----//

package br.ufc.frameworkkotlin.model.mapek.observer

interface IPlanningObserver {
        fun update()
}